README.md
src/components/connector.js
test/components/connector.spec.js

Rather then accepting an Array of selector functions accept only a single function
that returns an object. This object may specify multiple keys in order to return
multiple slices of store state.
ref: rackt/redux#387

Refactor selector(s) api

---

README.md
src/components/connector.js
src/components/ngRedux.js
test/components/connector.spec.js

* Expose store methods on ngRedux
* Remove getStore
* Remove disableCaching from connector

Refactor ngRedux's api

---

README.md
examples/counter/components/counter.html
examples/counter/components/counter.js

`vm` is very bad choice to name a `controllerAs`. I know that people uses it, but we saw that it was not that good because it defeats half of the purpose (being able to identify from where the variable comes from).
This new name makes the template much much easier to read.

Change vm for something else

---

examples/counter/package.json
examples/counter/webpack.config.js

This simplifies the webpack by removing all the react stuff only. Also structured the bottom code a bit better.
Also I removed the `webpack` execution from the `package.json` because that delays the server execution and will create the `dist` folder without need.

Simplify webpack config

---

index.d.ts

Filename chosen to leverage typescript's default definition file strategy for npm packages. Definitions based upon this discussion: https://github.com/wbuchwalter/ng-redux/issues/32

Adding a typescript definition file. 

---

index.d.ts

Convert typescript typings to an external module.
Resolves #44

Fix typings in packaged index.d.ts

---

src/components/ngRedux.js

The original redux `createStore` function allows to pass an initial state, but nothing allows us to so with `ng-redux`
Thanks, for your work

Support initialState for createStore

---

README.md
src/components/ngRedux.js

Hi, 
This PR aims to solve this issue -> https://github.com/wbuchwalter/ng-redux/issues/75 but in a different manner. We've implemented a way to pass the reducer as a single Function or as an Object. This is extremely helpful because we can create the reducers as an angular services and initialize it in the .config.
The reducer object would accept a function or a string for its values. Using it as a string, we can later use $injector.get("myReducerAsService") and get it injected.
It'll work like this:
```angular.module("myapp").config([
"$ngReduxProvider", "Redux"
"ReduxThunk"
(
$ngReduxProvider, Redux, thunk
) ->
$ngReduxProvider.createStoreWith({reducerAsService: "reducerAsService", reducerAsFunctions: fnction(){}}, [thunk])
return
])```
Let me know what you think.
Thanks

createStoreWith accepts either a function or an object with reducers

---

README.md
src/components/connector.js
test/components/connector.spec.js

A recently (a couple of months ago) supported feature from react-redux: `mapStateToProps` can return a function (invoked immediately) to allow per-instance memoization (selectors created specifically for a component instance). It simply creates a closure.

Support mapStateToTarget thunks

---

index.d.ts

This makes the type definition consistent with the documentation.
This 4th parameter represents an optional initial state.

Type definition now includes a 4th parameter on createStoreWith

---

package.json
src/components/connector.js
src/components/ngRedux.js
test/components/connector.spec.js

Ref: #129 #141
Replacement for original #129 solution. I'm replacing lodash's assign with `Object.assign` which copies over not only object keys/values but also Symbols.

fix: Replace lodash assign with Object.assign for symbol copy

---

package.json

The `./node_modules/.bin` works fine; however, it's preferred to use `npm bin`. Unfortunately `\`npm bin\`` doesn't work on Windows machines so I'm switching to just using the binaries directly. The upside of doing that is that NPM automatically prepends PATH with `./node_modules/.bin` contents so there is no reason to refer to them directly.

feat(scripts): Use NPM path resolution over custom paths to binaries

---

package.json

`build:min` is not setting production environment.
So this causes to log to the console even when building for production plus we are not getting webpack to optimize accordingly for prod.
>   You are currently using minified code outside of NODE_ENV === \'production\'.                                                                                           This means that you are running a slower development build of Redux.                                                                                      
You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.' 
@AntJanus 
We probably want to upgrade to a newer version of …

chore(build): set production environment

---

index.d.ts

Now we should be able to import ng-redux v3.5.x UMD module in typescript like this : 
```typescript
import * as ngRedux from "ngRedux";
```
Issue #153

Fix: update typings to fit with umd module

---

package.json
rollup.config.js

Fix for https://github.com/angular-redux/ng-redux/issues/156:
So there were 2 issues, first the `replace` plugin has to go before other plugins such as `commonjs`.
Also we had `browser` in package.json which Webpack will default to when resolving modules, so instead of resolving to `lib/ng-redux.js` (main) or `es/ng-redux.js` (module) it was resolving to `dist/ng-redux.js` which we build with env set to `development` https://github.com/angular-redux/ng-redux/blob/e1973f7d95059ec6f36259d972c9e69170f248ec/package.json#L20
FYI @maxlapides

fix(build): Removed browser entry from package.json

---

src/components/ngRedux.js

There is an existing issue when using ng-redux with [redux-first-router (RFR)](https://github.com/faceyspacey/redux-first-router).
When first loading the page RFR dispatches an action for the matched route. Due to how ng-redux creates the store this action is not passed to the registered middleware. I tested creating the store separately and passing this into ng-redux using the method outlined at the end of #19 but this then caused the digest loop to not be updated with the new state (due to the digestMiddleware not being added to the same middleware chain).
These changes to store creation mean the store is created as per the redux documentation and the middleware is initialised at the same time as the other store enhancers, thus preventing the action being swallowed.
This is very much an …

Adjust store creation to resolve issue with redux-first-router

---

index.d.ts

Changed the return type of subscribe(listener: Function) since redux
defines it as "Unsubscribe". Although using Function works, it may result
in TypeScript errors in certain use cases.
http://redux.js.org/docs/api/Store.html#subscribe

Changing subscribe's return type in Reducer

---

commitlint.config.js
package.json
yarn.lock

Setup Husky to lint commits, this adds commit-hooks to enforce conventional commit messages.

chore: lint commit messages

---

src/components/ngRedux.js
src/components/providedStoreMiddleware.js
src/components/storeWrapper.js

For #19 
_This started as a fork of #185._
- adds ability to provide an existing redux store instead of always creating a new one.
- when a store is provided, a local copy is made within ng-redux which is always updated with the full state of the primary store.
- dispatches _to_ the ng-redux copy are proxied back to the primary store via middleware.
Credit to @AntJanus for getting the ball rolling on this. I couldn't think of a better solution to the problem, but open to suggestions.
@AntJanus, unlike your implementation, i stuck to always returning the ng-redux store and just proxying dispatches back up instead of returning the merge of the provided store with the patched in subscribe method from the ng-redux store. If this isn't optimal, let me know.
@deini, you were mentioned in the …

feat(lib): provide store functionality (resubmitted)

---

.gitignore
README.md
package.json
rollup.config.js

BREAKING CHANGE: we aren't including redux to our umd build anymore.
Also added back the umd (dist) build since we still need to support it,
but it will be .gitignored
Added some bower support workaround in Readme
Closes https://github.com/angular-redux/ng-redux/issues/70

chore(build): makes redux a peerDependency

---

examples/counter/webpack.config.js

I've experienced problems when trying to launch the example project using Node@8.9.4/npm@5.6.0.
The solution was found here : https://github.com/webpack/webpack/issues/3242

Resolution of problem with some versions of npm/node

---

.gitignore
.idea/vcs.xml
README.md
package.json
src/components/digestMiddleware.js
src/components/ngRedux.js
test/components/digestMiddleware.spec.js

In my huge app, I have a lot of stimulations that modify the store and each one lead to a digest (via $rootScope.$evalAsync). The accumulation of digests considerably affect the performance of the application. 
We added a use of lodash.debounce in the digest middleware to avoid digesting too much.
- add lodash.debounce to the dependencies
- Use of lodash.debounce in the digest middleware
- Creation of a config for ngRedux
- Documentation of the config
- unit test for the debounce
- Correction of a problem with redux-thunk in ngRedux.js
```javascript
import angular from 'angular';
angular.module('ngapplication').config(($ngReduxProvider) => {
'ngInject';
// eslint-disable-next-line
$ngReduxProvider.config.debounce = {
wait: 250,
maxWait: 500,
};
});
```
Thx for your usefull lib ;-)

Debounce of the digests triggered by store modification

---

index.d.ts

@AntJanus per #200 updates the types for `connect` to allow for a null first argument in the event that your component does not require a `mapStateToThis` function. 
Also, makes various updates to the types, and adds type annotations (taken from redux) for an improved intellisense experience. Updates to the types themselves include:
- replacing Reducer, MiddlewareArg, and Middleware with more precise types taken from redux typings
- removing getReducer, which is no longer part of the redux API (so far as I can tell)
- indicate that connect returns `Unsubscribe` 
- [replace references to `Object` with the non-primitive `object` type](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html), in `mapDispatchToTarget` - though these types could definitely be …

improve types

---

README.md

First of all, thanks guys for creating and maintaining this project, it has helped me tremendously migrating from AngularJS to React.
I thought about adding an example to the README to include the usage of provideStore (introduced by https://github.com/angular-redux/ng-redux/pull/187).
I stumbled upon it while reading the source code, but it's such a useful method that it's a shame if people miss it just because it's out of the docs.

feat(chore): document provide store functionality

---

package-lock.json
package.json
src/components/connector.js
src/components/digestMiddleware.js
src/components/ngRedux.js
test/components/connector.spec.js

Closes #203 
passes tests.
This PR does a couple of things:
1. allows Redux 4 to be a peer dependency
2. updated lodash to newest version to bypass a security warning
3. unified lodash loading functions to use the all-encompassing `lodash` package; however, it only pulls in and compiles with the functions ng-redux uses

chore(lib): update lodash and redux dependencies

---

README.md
index.d.ts
src/components/ngRedux.js

This allows user to have full control over creating the store. This is important since some enhancers rely on ordering and needs to be first in list. Without having control over store creation this is not possible: ngRedux always sets the middlewares first.

feat(store creator callback): provide callback for creating store

---

src/components/connector.js
test/components/connector.spec.js

Allow connect to consume an ES6 module as the second parameter.
Motivation:
ES6 modules are more and more common in web development, and, from what I know, there are no reasons to not allow using them here. This patch is required for one of our internal projects to enable us to use the newest Webpack, so I hope that it will be found useful.
Questions:
Is the test enough to emulate the behaviour of an ES6 module in the NodeJS environment?

Allow mapDispatchToTarget to be an ES6 module

---

package-lock.json
package.json

Use the caret (^) operator to allow any version of lodash with a version over the specified
version (4.17.13).  This means that when this package is installed alongside other packages
depending on a higher version of lodash, the shared lodash dependencies can be deduped properly
across all dependents.
The caret also ensures that this package will not automatically upgrade to 5.x versions of
lodash (the next major version).
If it's preferred, I can also use the tilde (~) - this will lock the version to the current minor version.  I figured the caret would be okay, given that the other dependencies were locked with the caret.
**Motivation**: One of our applications is currently depending on multiple versions of lodash, even after using `npm dedupe`.  It's not terrible - this project does a …

chore: remove precise locking of lodash dependency

---

package-lock.json
package.json

Updating lodash to fix vulnerability affecting lodash versions < 4.17.17 
See https://snyk.io/vuln/SNYK-JS-LODASH-608086

chore(dependencies): updating lodash version

---

src/components/ngRedux.js
src/components/storeWrapper.js

This PR registers an unsubscribe callback with `$rootScope.$on('$destroy', ...)` in order to prevent the memory leak identified in https://github.com/angular-redux/ng-redux/issues/247.

unsubscribe from provided store when AngularJS app is destroyed
